### ISSUE TITLE
chromecast

### ISSUE THREAD

**Issue by leonard3333** [podStation/podStation#103]
Not really an issue/bug, more a feature request. It would be good to be able to cast. This seems to be supported. That is, from Chrome I can select Cast, and send the podcast to my amp. However, it does not work (no sound.)

**Comment by dellagustin** [comment]
There is already one open issue regarding this feature request, #1
I did some tests, but as I do not have a chromecast, I can't implement and test :(
I will close this issue, but you can subscribe to #1 to get notifications.

**Comment by leonard3333** [comment]
Thanks Guilherme. I have one, obviously, but only one - so I can't post you
a spare. Sorry. Anyways, I like your product a lot.

Can I ask a favour, unrelated to podcasts. I have a Recipe System that -
for whatever reason - I'm having trouble just getting simple feedback from
people. Mostly, I think, because I've approached chefs who tend to be
computer illiterate. (Or maybe my product is crap,d they're embarresed for
me.) Anywauys, I just want feedback, anything whatsoever. Easy to setup,
easy to use, climsy. Whatever. As long as it's honest feedback.

The product is this: Leo Recipe System.
https://www.leorecipesystem.com/

I'm willing to give you a free copy, so long as within a month or two you
give me some sort of feedback.

Let me know.

Leonard
