### ISSUE TITLE
Add integration with rescroller chrome extension

### ISSUE THREAD

**Issue by dellagustin** [podStation/podStation#116]
asked by a user, sent by e-mail.

https://chrome.google.com/webstore/detail/rescroller/ddehdnnhjimbggeeenghijehnpakijod
https://github.com/davidofwatkins/rescroller

**Comment by 152902** [comment]
Thanks for adding this!

**Comment by dellagustin** [comment]
I opened an issue on the rescroller repository to contact the authors and see if it is possible to integrate.

https://github.com/davidofwatkins/rescroller/issues/4

**Comment by 152902** [comment]
Thanks.

**Comment by dellagustin** [comment]
Hello @Ani-Xan, due to technical limitations it would be very difficult to implement this, rescroller cannot inject code in other extensions.

There are ways of doing it, but the effort would be too much for both rescoller and podStation, so unfortunately I will not implement this one.

**Comment by Ani-Xan** [comment]
@dellagustin Ok! I understand. At the time of your reply, I have actually stopped using the Rescroller extension and this would not benefit me. But thank's for telling me! 😃
