### ISSUE TITLE
Support for itunes feed

### ISSUE THREAD

**Issue by Semitalis** [podStation/podStation#117]
It seems that there is no support for an RSS feed with itunes schema, e.g:
```
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:cc="http://web.resource.org/cc/"
    xmlns:content="http://purl.org/rss/1.0/modules/content/" 
    xmlns:googleplay="http://www.google.com/schemas/play-podcasts/1.0"
    xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
    xmlns:media="http://search.yahoo.com/mrss/"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" version="2.0">
  <channel>
    <googleplay:block>yes</googleplay:block>
    <itunes:block>yes</itunes:block>
      <item>
        <title>(Plus) Mikrotransaktionen sind nicht böse, nur gefährlich</title>
        <itunes:title>(Plus) Mikrotransaktionen sind nicht böse, nur gefährlich</itunes:title>
        <pubDate>Sat, 04 Mar 2017 08:00:00 +0200</pubDate>
        <guid isPermaLink="false">
          <![CDATA[ 3E4524AAEBA92CBC3788862BC1B8D2A2 ]]>
        </guid>
        <link>
          <![CDATA[ https://www.gamestar.de/artikel/gamestar-podcast-plus-folge-1-mikrotransaktionen-sind-nicht-boese-nur-gefaehrlich,3310269.html ]]>
        </link>
        <itunes:image href="https://images.cgames.de/images/gamestar/4/podcast-cover-plus-1_6011798.jpg"/>
        <description>
          <![CDATA[ Weil wir zutiefst selbstironische Menschen sind, haben wir uns für die erste plus-exklusive Episode gleich ein passendes Thema ausgesucht: Geld her! Es geht nämlich um Echtgeld-Shops, Mikrotransaktionen und Geschäftsmodelle im Allgemeinen. ]]>
        </description>
        <content:encoded>
          <![CDATA[ Weil wir zutiefst selbstironische Menschen sind, haben wir uns für die erste plus-exklusive Episode gleich ein passendes Thema ausgesucht: Geld her! Es geht nämlich um Echtgeld-Shops, Mikrotransaktionen und Geschäftsmodelle im Allgemeinen. ]]>
        </content:encoded>
        <enclosure length="64298195" type="audio/mpeg" url="http://traffic.libsyn.com/gamestar/GS_Plus_Podcast_Folge_1.mp3"/>
        <itunes:duration>01:06:31</itunes:duration>
        <itunes:explicit>clean</itunes:explicit>
        <itunes:keywords/>
        <itunes:subtitle>
          <![CDATA[ Mit Michael Graf, Dimitry Halley und Maurice Weber ]]>
        </itunes:subtitle>
        <itunes:summary>Weil wir zutiefst selbstironische Menschen sind, haben wir uns für die erste plus-exklusive Episode gleich ein passendes Thema ausgesucht: Geld her! Es geht nämlich um Echtgeld-Shops, Mikrotransaktionen und Geschäftsmodelle im Allgemeinen.</itunes:summary>
        <itunes:episode>1</itunes:episode>
        <itunes:episodeType>full</itunes:episodeType>
        <itunes:author>GameStar</itunes:author>
      </item>
...
```

Resulting subscription looks like this and fails to update:
![image](https://user-images.githubusercontent.com/9306844/84091741-9d569400-a9f5-11ea-8a00-6245d2edef57.png)

Could we get this working? Would be highly appreciated, thanks! Love this extension by the way 👍

**Comment by dellagustin** [comment]
Hi @Semitalis, thank you for the compliments.

itunes schema should not be a problem, I subscribe to many podcasts that use it, so I suspect that the problem is something else.
I see that your podcast has authentication, that could be related to the problem somehow.

Can you check the logs of the background page and see what errors appearing there wen you try to update the feed?
![image](https://user-images.githubusercontent.com/260113/84388991-ba59b580-abf5-11ea-8918-2511e38fdfc5.png)

![image](https://user-images.githubusercontent.com/260113/84389180-f856d980-abf5-11ea-9e3c-39e08e48138f.png)

**Comment by Semitalis** [comment]
Sorry, for getting back so late, but here is the console log:
![image](https://user-images.githubusercontent.com/9306844/84608536-3c2a3700-aeb3-11ea-962a-9898b2f94b1f.png)

**Comment by dellagustin** [comment]
Hi, I am sorry to say that this error messages do no help much, they are "normal".
Maybe check in the network tab if the request to your feed's address is being complete with success or not.

**Comment by Semitalis** [comment]
Yeah the status code is 404 and the returned content seems to be the normal gamestar.de page html:
![image](https://user-images.githubusercontent.com/9306844/84827346-9dbde300-b024-11ea-84c2-68af0f0d40f9.png)
![image](https://user-images.githubusercontent.com/9306844/84827452-c9d96400-b024-11ea-8c12-71cbc766ae00.png)

**Comment by Semitalis** [comment]
Ah, I figured out that when I copy the requested URL, I get the same error until I remove the additional "&_=1592337176839" at the end. This seems to be a random timestamp or similar to prevent caching mechanics? This seems to cause the issue here.

**Comment by Semitalis** [comment]
When I enable AJAX caching, e.g:
![image](https://user-images.githubusercontent.com/9306844/84827796-479d6f80-b025-11ea-9bd6-b0e4ef36bf3f.png)

it seems to work:
![image](https://user-images.githubusercontent.com/9306844/84827748-35bbcc80-b025-11ea-913e-8303eae53aec.png)

**Comment by Semitalis** [comment]
I wrote to the RSS feed supplier, whether they can simply support the no-cache timestamp addendum. Maybe an option to turn cache on as a user for a specific Feed would be handy nevertheless? :)

**Comment by dellagustin** [comment]
That is a very good analysis, thanks.
So, I never introduced the "&_=" query parameter on purpose, it was there since the beginning and since it did no harm I did not bother removing it, specially as RSS feeds are not something you would want to cache (normally).
I'll think about it, while we wait for a response from the provider.

**Comment by Semitalis** [comment]
The related RSS feeds finally support timestamps and I am now happily able to use them! :)

This issue can now be closed. Thanks!
