### ISSUE TITLE
Regarding changing the backgroung of Podstation webpage in Chrome

### ISSUE THREAD

**Issue by dheerajgoyalbsnl** [podStation/podStation#118]
Please guide how I can change the background of Podstation webpage in Chrome at my Desktop.

**Comment by dellagustin** [comment]
Hello, I am sorry I did not answer sooner.
I will need more details on this issue, can you please elaborate?

**Comment by dellagustin** [comment]
I'll close this one as it is inactive for a long time without details from the reporter.
Please reopen if you want to add more information.
