### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by dellagustin** [podStation/podStation#135]
It was requested in a few reviews, dark mode seems to be quite popular these days.

**Comment by ashishpatel1992** [comment]
Hi @dellagustin ,
Are there any restrictions on a colour scheme for dark mode? Or any specific instructions for it.
If not then I would like to work on this.

**Comment by ashishpatel1992** [comment]
@dellagustin  I am going to start working on this. Can you please assign it to me?

**Comment by ashishpatel1992** [comment]
Hi @dellagustin ,
I am almost about to finish it. I just want to know in which file do you store user preferences?
I am planning to store color scheme preference for the user.

**Comment by dellagustin** [comment]
Hi @ashishpatel1992, 

I store the options using the browser's sync storage (https://developer.chrome.com/extensions/storage).
Take a look at https://github.com/podStation/podStation/blob/d1688f2822c2a88fe1db4c5a3c4e1d79ea327f35/extension/background/entities/optionsManager.js, and https://github.com/podStation/podStation/blob/master/extension/ui/ng/controllers/optionsController.js.

Do you want to store only the information on whether to use the dark mode or not, or also the color scheme itself?
In principle I think the dark mode option would be synchronized across devices, so sync storage is a good place.

**Comment by ashishpatel1992** [comment]
Dark mode enhancements:
- [X] UI in dark mode
- [X] Darkmode switch button near Add feed
- [X] RSS feed icon image replaced with font awesome icon to make it compatible with dark mode
- [ ] Integration with browser's sync storage

![image](https://user-images.githubusercontent.com/652311/97834172-28b22800-1cfd-11eb-94be-9b42df5d7704.png)

I am still exploring a way to integrate Browser Sync for a `darkScheme` variable. I have never used angular before.
We will only be storing `True` and `False` for `darkScheme` variable.
Meanwhile, you can check out the changes. 
I will send a pull request

**Comment by dellagustin** [comment]
Released in v1.26.0.
