### ISSUE TITLE
[Feature Request] Play/Pause podcast from Extension Icon

### ISSUE THREAD

**Issue by ashishpatel1992** [podStation/podStation#151]
Play/Pause podcast by left-clicking extension icon would be nice. This will also toggle the player icon based on its current state.
If you are interested I can work on this.

**Comment by dellagustin** [comment]
Hi @ashishpatel1992 , thanks for the feature request.

Currently, if you left-click the icon it will bring bring a podStation tab into focus, or open a tab for podStation if there is no open tab for it already.

How would you implement this feature without overriding the current behaviour?

**Comment by ashishpatel1992** [comment]
Hi @dellagustin ,
The idea behind this is if the user hasn't clicked on podStation since opening the browser, it will open the podStation tab.
If the user has already opened the podStation since the beginning of the browser session and also has played the music at least once, then we can change the action to play and pause.

Also, I would like to know do we have any kind of analytics to know how many users use the right-click and how many users use left click?

**Comment by dellagustin** [comment]
> If the user has already opened the podStation since the beginning of the browser session and also has played the music at least once, then we can change the action to play and pause.

How would the user open the podStation page again in this case (in case the user closed the page)?

> Also, I would like to know do we have any kind of analytics to know how many users use the right-click and how many users use left click?

No, I only have analytics for the the usage of Play/Pause on the right click menu:
![image](https://user-images.githubusercontent.com/260113/97741058-756de700-1ae2-11eb-8a03-7851eb9ad49f.png)

**Comment by ashishpatel1992** [comment]
> How would the user open the podStation page again in this case (in case the user closed the page)?

Yes, you are right. The user won't be able to open podStation again. The only way would be to right-click and open. Maybe I need to come up with a better idea.
