### ISSUE TITLE
Implement support for podcast:funding

### ISSUE THREAD

**Issue by dellagustin** [podStation/podStation#159]
Reference feed: https://mp3s.nashownotes.com/pc20rss.xml
Documentation: https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#funding

Code references:
- https://github.com/podStation/podStation/blob/2bc006af81c61dac69e20f2d83b6c9b3986b9ad7/extension/background/entities/podcast.js#L304
- https://github.com/podStation/podStation/blob/2bc006af81c61dac69e20f2d83b6c9b3986b9ad7/extension/ui/ng/controllers/podcastsController.js#L51
- https://github.com/podStation/podStation/blob/2bc006af81c61dac69e20f2d83b6c9b3986b9ad7/extension/ui/ng/partials/podcasts.html#L58

**Comment by dellagustin** [comment]
Implemented with #161

**Comment by t-900-a** [comment]
Why wasn't rel-payment used instead?
http://microformats.org/wiki/rel-payment

**Comment by dellagustin** [comment]
Hello @t-900-a , I was not aware of it, I have created an issue about it: https://github.com/podStation/podStation/issues/244

If you have examples of podcast feeds that use this type of link, please share them with me in the issue.
