### ISSUE TITLE
use dark scroll bar when in dark mode

### ISSUE THREAD

**Issue by super-lurker** [podStation/podStation#162]
use dark scroll bar when in dark mode

**Comment by dellagustin** [comment]
Hi @super-lurker, thanks for your feature request.
Do you have any working examples on other web application that we could use as reference?

@ashishpatel1992 do you know how this could be implemented? feel free to take over if you are interested.

**Comment by ashishpatel1992** [comment]
Hello @dellagustin,
Sure. Please assign it to me. I will do that.

**Comment by dellagustin** [comment]
@ashishpatel1992 many thanks! it is assigned.

**Comment by super-lurker** [comment]
> Hi @super-lurker, thanks for your feature request.
> Do you have any working examples on other web application that we could use as reference?
> 
> @ashishpatel1992 do you know how this could be implemented? feel free to take over if you are interested.

i use this extension to make my scroll bar dark everywhere

https://chrome.google.com/webstore/detail/blending-scrollbar/ajjnokaolfbjimgelmdmdlijoclmjnag

unfortunately chrome doesn't let extensions work on other extensions :(

**Comment by dellagustin** [comment]
I integrated the pull request from @ashishpatel1992 today, it will be included when I release the next version.

**Comment by dellagustin** [comment]
Released in v1.29.0 - https://github.com/podStation/podStation/blob/master/docs/release_notes/v1.29.0.md
