### ISSUE TITLE
Unable to add or remove podcasts from Playlist

### ISSUE THREAD

**Issue by HackManMN** [podStation/podStation#168]
I used PodStation with no real problems for a couple years. 

Then it would no longer allow me to add any more items to my Playlist. Eventually I found that if I deleted some items from the Playlist (even though I hadn't listened to them yet) I was able to add the new item that I wanted.

It is now in the state where I only have three items in my Playlist. Clicking the "X" next to any of the three does not remove it from the Playlist. 

Also, clicking on the "+" on any podcast doesn't add it to the Playlist.

Summary: Unable to add or remove anything to/from the Playlist.

Both issues are present on multiple machines (so far tested on an ASUS ChromeBox and a Heier Chromebook, both running ChromeOS in the Chrome browser).

As a workaround, I am still able to page down about 30 pages to find the podcast I want to listen to and click the triangle "play" icon (without adding it to the Playlist).

**Comment by dellagustin** [comment]
Hi @HackManMN , thanks for submitting this issue here.

Can you please post a screenshot of the about section as the one below?
![image](https://user-images.githubusercontent.com/260113/99430086-29f07100-2909-11eb-8126-4d58d08948af.png)

**Comment by HackManMN** [comment]
![Screenshot 2020-11-17 at 12 21 28 PM - Display 2](https://user-images.githubusercontent.com/74617814/99430979-a49c9a80-28cf-11eb-96f5-e1f0cb65d39e.png)

**Comment by dellagustin** [comment]
Ok thanks, I knew this would happen one day, actually it took long enough.

Basically, your synch storage is 85 bytes over quota (the quota is 102400 bytes, https://developer.chrome.com/extensions/storage#property-sync).

This is a bit weird, it should never go over quota, I expected the software to automatically stop updating things when it goes over quota. Now that it is over quota, I think even after you remove something from the playlist, the resulting storage is still over quota.

I am thinking how to solve this.

In the meantime, can you please right click anywhere in the extension page, select Inspect in the menu, go to Console and run the following command?

`chrome.storage.sync.get((b) => console.log(b));`

then expand the first node and post a screenshot, it will look like this:
![image](https://user-images.githubusercontent.com/260113/99432633-b6e8f980-290c-11eb-94b4-c490cb5f323f.png)

**Comment by HackManMN** [comment]
![Screenshot 2020-11-17 at 1 12 59 PM - Display 2](https://user-images.githubusercontent.com/74617814/99436205-c9e0d700-28d6-11eb-98ab-92776ac4ef4b.png)

**Comment by dellagustin** [comment]
Seems like you have a lot of episodes in progress, can you go to the list of podcasts in progress and try to use the stop button, see if the episodes are removed from the list.
![image](https://user-images.githubusercontent.com/260113/99451402-71372b80-2922-11eb-87d5-c7e0461b6228.png)
if it works, stop some of podcasts to regain space.

**Comment by HackManMN** [comment]
Wow. That was a big list of episodes in progress. Haha. about 3 a week all the way back to early 2017.

I'll have to break my habit of starting a new podcast as soon as one is 99% done. :-) 

And yes--that fixed it. I was able to remove the three podcasts that were still in my Playlist and also was able to add podcasts to my Playlist.

Thanks for your assistance.

**Comment by dellagustin** [comment]
I know the feeling, I guess I need to implement a feature to warn the user that the quota is near to be reached.
I'll close the issue since it is solved.
