### ISSUE TITLE
Overflowed title text in episode Player

### ISSUE THREAD

**Issue by ashishpatel1992** [podStation/podStation#174]
There is an overflowed episode Player when the title is too long

![image](https://user-images.githubusercontent.com/652311/99886597-c4331a80-2c63-11eb-8846-c6864bd5cd03.png)

Suggestions:

1.  Take the rest of the text into new line i.e. text wrapping
2.  Show a `...` at the end and display the only text which fits, and upon hover over show the full text (i.e. add `title` attribute)

**Comment by dellagustin** [comment]
Good catch, I think I saw this before, but I forgot to put it on the issue list.

Thanks for reporting and for the suggestiions.
