### ISSUE TITLE
Title's width is uneven in podcast list 

### ISSUE THREAD

**Issue by dhara03** [podStation/podStation#177]
![title-width-issue](https://user-images.githubusercontent.com/64042104/100005219-9fb77980-2dee-11eb-8058-307729778fd1.png)

Suggestion: 

![title-width-issue-solution](https://user-images.githubusercontent.com/64042104/100005266-afcf5900-2dee-11eb-8922-4d70af8a74c5.png)

**Comment by dellagustin** [comment]
Hi @dhara03, thanks for reporting it, feel free to tackle it if you know how to fix it.

**Comment by dhara03** [comment]
Hello @dellagustin , thanks for letting me work on this. 
I have fixed it and it's working properly in light & dark both modes.

Regarding the title, I found another issue which I'm posting here.

![title-issue](https://user-images.githubusercontent.com/64042104/100095552-ad1d4400-2e80-11eb-862d-4e6bd94b9be7.png)
Suggestion:
![title-issue-soltion](https://user-images.githubusercontent.com/64042104/100095710-eb1a6800-2e80-11eb-8db6-3446729b436f.png)
I can work on this if you feel appropriate to change it.

**Comment by dellagustin** [comment]
Hi @dhara03, thanks for working on this.

Regarding https://github.com/podStation/podStation/issues/177#issuecomment-732953605, can you please report it as a separate issue?
I'll have to think about this one, on how to best handle this case.

**Comment by dhara03** [comment]
Yeah, sure.

**Comment by dellagustin** [comment]
Solved with #183.
