### ISSUE TITLE
Audio controls are overlapping the podcast list title when it is too long.

### ISSUE THREAD

**Issue by dhara03** [podStation/podStation#181]
![title-issue](https://user-images.githubusercontent.com/64042104/100115513-9e428b80-2e98-11eb-8750-e567ae437017.png)

Sugesstion:

![title-issue-soltion](https://user-images.githubusercontent.com/64042104/100115557-ab5f7a80-2e98-11eb-9df4-c70530682509.png)

And this will applies to the podcast list titles as well.

![title-overlap-darkmode](https://user-images.githubusercontent.com/64042104/100118595-ff1f9300-2e9b-11eb-9846-a68670f198f6.png)

![title-overlap-whitemode](https://user-images.githubusercontent.com/64042104/100118800-2fffc800-2e9c-11eb-9703-e8329b5dcaaa.png)

**Comment by dellagustin** [comment]
Hi @dhara03, thanks for creating the issue.

I'm not sure I like the empty space that results on moving the title down.

I did a test and "cheated" a bit, wrapping the title in a div and setting its max-width to 95%, the result looks ok, what do you think?
![image](https://user-images.githubusercontent.com/260113/100154244-90dfce00-2ea5-11eb-8be8-2e60814594c0.png)

**Comment by dhara03** [comment]
Hello @dellagustin , I also tried decreasing the title width which solves the issue. But as you said "cheated a bit" so I thought let's not mess with the title's width and try adding/removing some space as described in SS. But if you have no problem and find it appropriate we can go with this solution. Either way, it's not affecting any other layout design so there's no harm in applying this.

Btw, there's no need to wrap the title in div. By just adding display: block; max-width: 95%; to respective title's <a> will solve the issue.

**Comment by dhara03** [comment]
And I have just noticed that the podcast image is uncertain. Sometimes it is displaying sometimes not. For example the SS you posted here is with an image on the left side of the title. But when I checked the same podcast in live version of chrome extension it's not there. I guess there's some conditional issue is there.

![Desktop-screenshot](https://user-images.githubusercontent.com/64042104/100223219-3431f100-2f41-11eb-9b06-0d1a72ac15f3.png)

**Comment by dellagustin** [comment]
Let's go with limiting the title width then, I think it looks better.

> Btw, there's no need to wrap the title in div. By just adding display: block; max-width: 95%; to respective title's will solve the issue.

good to know, it sounds better than wrapping in a div.

**Comment by dellagustin** [comment]
Regarding https://github.com/podStation/podStation/issues/181#issuecomment-733657040, there is actually a logic behind it, my screenshot is from the "Last episodes view", there I show the image for the corresponding podcast, as you will have in the list episodes from different podcasts.

In your screenshot, the view is for a single podcast, and there I do not show an image for each episode.

Some feeds will provide an image per each episode, but I did not implement support for that yet.
There is an open issue for this topic #167 , we can follow up there if you are interested.

**Comment by dhara03** [comment]
Hi @dellagustin , Yes sure. I can work on #181. And regarding #167, I guess I'm not capable enough to work on this.

**Comment by dhara03** [comment]
Hello @dellagustin , I have committed changes regarding this issue and send PR. Please check it.
