### ISSUE TITLE
Podcast title layout is not looking proper when title is too long

### ISSUE THREAD

**Issue by dhara03** [podStation/podStation#190]
Right now it is looking like this:

![Desktop-screenshot (2)](https://user-images.githubusercontent.com/64042104/102078599-31843680-3e31-11eb-96d1-17e62bcdb9d9.png)

Which we can design like this:

![Desktop-screenshot (1)](https://user-images.githubusercontent.com/64042104/102078657-49f45100-3e31-11eb-83f1-17c69252c3e2.png)

Or

![Desktop-screenshot](https://user-images.githubusercontent.com/64042104/102078679-511b5f00-3e31-11eb-9f80-08497c8c6629.png)

**Comment by dellagustin** [comment]
Thank you @dhara03 , I'm more inclined to the first option, but I actually have an idea that I'll need to sketch, will show you later.

**Comment by dhara03** [comment]
Okay @dellagustin , will like to see your sketch.

**Comment by dellagustin** [comment]
Hi @dhara03,

this is what I was thinking about:
![image](https://user-images.githubusercontent.com/260113/102139753-8be7bc00-3e5e-11eb-8c02-17e2baad8961.png)

It does not look as good as I expect, I would go with your fist option, to keep the menu on the right side.
But I would only apply this to this view, in the other views (podcasts, last episodes), I would keep it as it is, as it saves some vertical space.

**Comment by dhara03** [comment]
Hello @dellagustin , I got your point. Let me check how can I apply my suggested layout only when episodes lists are displaying.

**Comment by dhara03** [comment]
Hi @dellagustin , to solve this issue I'll need your small help. Can you please add a conditional class to "contentBoxMenu" id? I tried to add it but it's not working out. I need one class that should appear only when all the episode lists are displaying. It should not appear when last episodes, podcast list is there. You can add any relatable class name to this div.

**Comment by dellagustin** [comment]
Hello @dhara03 , I'll take a look at that.

**Comment by dhara03** [comment]
Sure, thanks.

**Comment by dellagustin** [comment]
Hi @dhara03, I have been reconsidering https://github.com/podStation/podStation/issues/190#issuecomment-744739519.
I think I am gonna go with that.
Take a look at https://github.com/podStation/podStation/pull/193.
I did some small changes to the layouts too that makes it a bit better.

**Comment by dhara03** [comment]
Hi @dellagustin , I checked #193 . Yup this looks better. 
Here I would like to suggest you that please give all CSS by adding a class name for better CSS specificity. And avoid giving inline CSS so that you don't have to give !important to override your CSS in the future.

**Comment by dellagustin** [comment]
@dhara03 done.
