### ISSUE TITLE
Side effect from #193

### ISSUE THREAD

**Issue by dellagustin** [podStation/podStation#196]
The change introduced in #193 also introduced a small side effect.

In episode lists the phrase "All episodes from ..." now shows the podcast name in a new line.

![image](https://user-images.githubusercontent.com/260113/103296904-67abe380-49f7-11eb-92f1-61893796b8e8.png)

**Comment by dhara03** [comment]
Hi @dellagustin ,

This issue is coming because of an extra `<br>` tag in the structure. Just remove that tag from particular templates it will display on the same line.

![Issue-SS](https://user-images.githubusercontent.com/64042104/104122459-227aa080-536b-11eb-9ae3-dd854d18aaff.png)
