### ISSUE TITLE
How about a thumb slider drag in the player?

### ISSUE THREAD

**Issue by pperrin** [podStation/podStation#2]
It would be good to be able to jump around a podcast by clicking on the position in the display. Currently clicking in that area just restarts the podcast.

**Comment by dellagustin** [comment]
Hi Paul, 

Can you please add some more details, a screenshot for instance?
And also the podcast name and episode where it happens?
This is just to be sure, that I understood your issue well.
If I did understand it well, it was already supposed to work like that, and this would be a bug.

Best Regards,
Guilherme.

**Comment by pperrin** [comment]
Ok - I tried to recreate the problem and it does seem to work with a thumb slide now -- I have *loads* of podcasts from loads of sources, I'll just have to wait for it to do it again (it was a very big podcast, maybe streaming or something) - I'll update if it happens again...

**Comment by dellagustin** [comment]
Ok, it may have been a streaming issue from the podcast.
I'll mark it as non reproducible for the moment, if you manage to reproduce it, please let me know.

**Comment by dellagustin** [comment]
No action for long time, so I'll close it.
If it happens again please create a new one.
