### ISSUE TITLE
Podcast list UI enhancement

### ISSUE THREAD

**Issue by dhara03** [podStation/podStation#203]
Hi @dellagustin , We can improve all list UI looks. Please look at the below SS.

![Screenshot (90)](https://user-images.githubusercontent.com/64042104/105631307-ecaddf80-5e73-11eb-8569-e546a7b2ffcd.png)

As compared to this, the next one is looking more clean design.

![Screenshot (93)](https://user-images.githubusercontent.com/64042104/105631562-0d2a6980-5e75-11eb-8fc7-ed164b46e962.png)

**Comment by dellagustin** [comment]
Hello @dhara03 , thank you for the mock up.
To be honest, I prefer the current design with the shadow, then the new one without it.

**Comment by dhara03** [comment]
Okay @dellagustin , we can keep the same layout. Thanks for your opinion on this.
