### ISSUE TITLE
Feature request - forward / backward skip shortcuts

### ISSUE THREAD

**Issue by rudymack** [podStation/podStation#334]
Youtube allows me to move forward and backward using left and right arrow keys which I find very helpful for repeating certain parts or looking for a certain passage. I would find that feature very helpful in podStation as well.

**Comment by dellagustin** [comment]
Hello @rudymack , thanks for the request.
There is already a similar feature request: https://github.com/podStation/podStation/issues/144
I cannot promise I will work on this anytime soon, but it is a good feature to have.

**Comment by dellagustin** [comment]
I'll close this one and handle it with #144 .
