### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by emersonmellado** [podStation/podStation#4]
Hello,

Awesome job on this extension. I am loving it!

Just one question, Is there any shortcut support or personalization planned?

thanks!

**Comment by dellagustin** [comment]
Hi Emerson, thanks for the feedback.
What kind of shortcuts do you have in mind?

**Comment by emersonmellado** [comment]
Wow, quick response. Awesome!

for example, a global shortcut to play/pause, just to avoid having to click the icon and then find the small play/pause button to click on it. (I am a dev also, so lazy behaviour detected haha)

I saw somewhere that you use the global play/pause of a media keyboard, but I don't have that on my laptop for some reason so wondering if there is another way.

Thanks!

**Comment by dellagustin** [comment]
There is already a shortcut for that, but chrome does not allow me to deliver it as global. You can activate it though: go to the extension manager and look for keyboard shortcuts on the bottom right. If you do not find it I'll post a Screenshot for you when I get to the PC.

**Comment by dellagustin** [comment]
Oh, sorry, I misread it, now I see that you do not have the media keys on your notebook. I'll check if there are alternatives.

**Comment by emersonmellado** [comment]
Wow, it works!

Chrome allow overriding to the Media global shortcut.

Thanks, man!
