### ISSUE TITLE
Botão remover/oculta

### ISSUE THREAD

**Issue by esbap** [podStation/podStation#5]
Gostei bastante do seu projeto e gostaria de sugerir um botão para ocultar ou remover os episódios que ja foram ouvidos ou que não quero ouvir da lista de últimos episódios.

Sou programador e gostaria de contribuir, mas não entendo nada sobre as ferramentas que esta utilizando. Tem alguma coisa que eu possa fazer pelo projeto?

**Comment by dellagustin** [comment]
Olá @devplusti , 

Obrigado pela sua sugestao.
Já tenho uma issue igual no bitbucket, onde mantenho as issues do podStation:
https://bitbucket.org/dellagustin/podstation_chrome_ext/issues/49/feeds-mark-episodes-as-listened

O problema para implementar essa sugestao é que o podStation foi concebido com a premissa de que os dados do usuário deveriam ser guardados no armazenamento sincronizado do google, para que se possa usar o programa em diferentes computadores, mas com as mesmas informaçoes (lista de podcasts, playlists, etc...)

Esse armazenamento sincronizado do google é muito limitado, somente 200 KB, e se eu começar a guardar essa informaçao de quais podcasts foram ouvidos, certamente acabará logo.

Se você quiser colaborar com o projeto, pode ver a lista de issues abertas aqui:
https://bitbucket.org/dellagustin/podstation_chrome_ext/issues

O que você precisa é saber, ou aprender, JavaScript, HTML, AngularJS e a api de extensoes do chrome.

Atenciosamente,
Guilherme.
