### ISSUE TITLE
Status Icons

### ISSUE THREAD

**Issue by benyjr** [podStation/podStation#6]
Hello,

Would it be possible to change the player status indicator from |> and || to ► and ▐▐ respectively?

As is, they are difficult to interpret. I tried to make the changes for myself locally, but could not find where they are located in the code.

**Comment by dellagustin** [comment]
Search for badge here: https://github.com/podStation/podStation/blob/master/background/entities/audioPlayer.js
I'll take a look with more time later

**Comment by benyjr** [comment]
Closing this issue.  It's not super important.

**Comment by dellagustin** [comment]
Implemented in 19b9b829ef897e166bf2aa1fd18d7c0f6a7f5456
It will be delivered in the next release.

**Comment by dellagustin** [comment]
This is how it looks like now:
![image](https://user-images.githubusercontent.com/260113/34417003-82c52f9e-ebf6-11e7-9f6e-0be94d80ed88.png)
![image](https://user-images.githubusercontent.com/260113/34417012-902ba7d0-ebf6-11e7-92c2-5953542ee0c2.png)

**Comment by benyjr** [comment]
Looks awesome!
